name: CI2

on:
  pull_request:
    # By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened
    branches: [main]

jobs:
  cache_dependencies_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Get yarn cache directiory path
        id: yarn_cache_dir_path
        run: echo "::set-output name=cache_dir::$(yarn cache dir)"
      - name: Create cache key
        id: yarn_lock_cache
        run: echo "::set-output name=hash::${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}"
      - name: Cache yarn cache dir
        uses: actions/cache@v3
        id: cache_dependencies
        with:
          path: ${{ steps.yarn_cache_dir_path.outputs.cache_dir }}
          key: ${{ steps.yarn_lock_cache.outputs.hash }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
    outputs:
      yarn_cache_dir: ${{ steps.yarn_cache_dir_path.outputs.cache_dir }}
      cache_key: ${{ steps.yarn_lock_cache.outputs.hash }}

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: cache_dependencies_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Check yarn cache
        uses: actions/cache@v3
        id: cache_dependencies
        with:
          path: ${{ needs.cache_dependencies_job.outputs.yarn_cache_dir }}
          key: ${{ needs.cache_dependencies_job.outputs.cache_key }}
      - name: Lint code
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - cache_dependencies_job
      - lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Check yarn cache
        uses: actions/cache@v3
        id: cache_dependencies
        with:
          path: ${{ needs.cache_dependencies_job.outputs.yarn_cache_dir }}
          key: ${{ needs.cache_dependencies_job.outputs.cache_key }}
      - name: Build code
        run: yarn build

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - cache_dependencies_job
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Check yarn cache
        uses: actions/cache@v3
        id: cache_dependencies
        with:
          path: ${{ needs.cache_dependencies_job.outputs.yarn_cache_dir }}
          key: ${{ needs.cache_dependencies_job.outputs.cache_key }}
      - name: Test code
        run: yarn test
